name: Test

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        slow_division: [0, 1]
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.compiler }} (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler }} libomp-dev llvm
      - name: Install gcc (macOS)
        if: matrix.os == 'macos-latest' && matrix.compiler == 'gcc'
        run: |
          brew update
          brew install gcc
      - name: Install llvm (macOS)
        if: matrix.os == 'macos-latest' && matrix.compiler == 'clang'
        run: |
          brew update
          brew install llvm libomp
      - name: Run test suite
        run: make test N=11 SLOW_DIVISION=${{ matrix.slow_division }}
        env:
          CC: ${{ matrix.compiler }}
